/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    
	stores: ['List'],
	
    views: [
        'Main',
        'plantsMain',
        'searchPlants',
        'detailResult',
        'resultInfo',
        'galleryBoard',
        'galleryPreview',
        'galleryWrite',
        'myPage',
<<<<<<< HEAD
=======

>>>>>>> Img Button Add
        'MyPage01',
        'overlaySelect',
        'testPage',
        'boardInput' 
<<<<<<< HEAD
=======

>>>>>>> Img Button Add
    ],
    name: 'plants',
    controllers: [
        'searchController',
        'galleryController',
        'myPageController'
    ],

    launch: function() {
    	Ext.fly('appLoadingIndicator').destroy();
        Ext.create('plants.view.Main', {fullscreen: true});
    }

});
